### ISSUE TITLE
Ore Mining Animations

### ISSUE THREAD

**Issue by Brand24376** [justi2023567/CodeFactory#28]
Add all the animations that are gonna be used when mining the ores. This includes: All ore art (inventory and 3d models), the stone mining animation, the stone exploding into multiple bits when mined, the stone cells disappearing with a fade out animation to reduce lag, and have the stone have a tiny exploding animation to have the stone cells spread out a bit when you mine the ore. 
All tasks above have been completed.

Ores get changed to their respective ore dynamically and when the ore breaks there's a model of the respective ore that appears. By respective ore I mean the code that selects what ore is going to be dropped when the ore gets broken. The code will have to be moved because right now the ore only gets randomized when the ore gets destroyed. This will also include making art for every ore.

**Comment by Brand24376** [comment]
Stone cells disappear, no animation on their disappearance.

**Comment by Brand24376** [comment]
Stone cells disappear with a fade out animation.

**Comment by mhoover0413** [comment]
Add crackling to the ores when being mined.

**Comment by Brand24376** [comment]
Added spark light effect when ore gets hit.

**Comment by Brand24376** [comment]
Logan did the 2nd paragraph of this issue shown in pull request #101 which I had to revert and fix since it had some issues and I merged both of our changes in pull request #103
