### ISSUE TITLE
Shop System 

### ISSUE THREAD

**Issue by justi2023567** [justi2023567/CodeFactory#8]
Allow item to be sold and then add to a money counter. Rare materials & higher quality materials (e.g. 75% purity or higher) will be sold for more. Includes selling and buying. This will just be the shop system and there will be a placeholder shop for now.

**Comment by Brand24376** [comment]
Started on the shop system by making a npc that you can only interact with when you are within its range. Still ne to implement the shop system.

**Comment by Brand24376** [comment]
Started on the dialogue system for the shop bot. It is currently broken so I need to fix that.

**Comment by Brand24376** [comment]
Started on the ui for the shop and made a gold pog art

**Comment by Brand24376** [comment]
Finished the barebones of the shop system
